### ISSUE TITLE
drawer is not closing on 3DTouch devices

### ISSUE THREAD

**Issue by DevBkIL** [react-native-community/react-native-drawer-layout#10]
on 3DTouch devices when you press the side overlay the drawer dosnt close..
but if tap really slightly it will work..
i had some issue with 3Dtouch devices that Touachables* nested in 2 scrollviews  dosnt respond to taps. maybe related the panResponder issue https://github.com/facebook/react-native/issues/3082

Live long and propsper :]

edit: i am using RN 0.39.1 and the latest react-native-drawer-layout (with the zIndex change)

**Comment by DanielMSchmidt** [comment]
Wow, okay. I have no possibility to test and verify this. It would be great if you or someone else with a device like this may test it. Would you mind doing a PR?

**Comment by DevBkIL** [comment]
i tested on iPhone 7,6s and the overlay dosnt respond,also on 6,5s and simulator the overlay respond

**Comment by DevBkIL** [comment]
the fix is pretty simple i made the change on the transform js file
you just need to add 
if(!dx || !dy)return false
in _shouldSetPanResponder at the top of the function and you good to go

**Comment by DanielMSchmidt** [comment]
@DevBkIL Would you mind opening a PR?

**Comment by DanielMSchmidt** [comment]
@DevBkIL Hey, any updates on this?

**Comment by DanielMSchmidt** [comment]
Should be fixed in `1.1.5`, can you verfiy?
