### ISSUE TITLE
Background overlay no longer showing

### ISSUE THREAD

**Issue by alxyuu** [react-native-community/react-native-drawer-layout#12]
After upgrading from 1.1.1 to 1.1.4, the background overlay no longer shows on iOS. As a result, tapping outside the drawer no longer closes it. Additionally, the drawer feels a bit awkward on android (I'm guessing since it's now pure js?) -- sometimes it will open partially and just stay that way.

I'm using it as part of ex-navigation and RN 0.41. I've locked my version to 1.1.1 in the meantime but this seems like pretty big issue.

**Comment by DanielMSchmidt** [comment]
Can you give an example, so that I can tackle the bug better? I tested it on [my demo app](https://github.com/DanielMSchmidt/DrawerLayoutExample) with exponent and everything works as expected. 

Bonus points for writing your own example project with exponent 😄

**Comment by DanielMSchmidt** [comment]
Hey @alxyuu, I just tested it on an android device and on an iOS simulator with the react-navigation example and it worked there. Could you tell me a bit more please?

**Comment by alxyuu** [comment]
sorry for the late update, here's an example project: https://github.com/alxyuu/react-native-drawer-layout-issue12

notice that if you change the `react-native-drawer-layout` version to 1.1.1 in `package.json` the dark background overlay returns when the drawer is open. make sure you run `npm install` and restart exponent after you change it.

it might be possible it's an ex-navigation bug (haven't played with react-navigation yet), but I'm just assuming it's related to this project since reverting the version fixed the issue. I can dig a bit more tomorrow.

edit: just to reiterate, the background overlay is an issue on ios only. The android issue I mentioned is a bit harder to demonstrate. I'm thinking it might have something to do with additional pan responders on the screen. I'll play with it a bit more and report back.

**Comment by DanielMSchmidt** [comment]
Thank you so much for your help @alxyuu 
Great work, could reproduce the bug and will fix it today 💪

**Comment by DanielMSchmidt** [comment]
I build a demo to test it with a copy of my implementation, for faster debugging: https://github.com/DanielMSchmidt/drawer-layout-wip  
The core problem is here: https://github.com/DanielMSchmidt/drawer-layout-wip/blob/master/drawerLayout.js#L157-L161 

The logging gave these results: 

1) render gets called at the right points of time
2) drawerShown is true at the right points of time
3) onLayout in the Touchable of the overlay gets called (x: 0, y:0, width: deviceWidth, height: deviceHeight)
4) setting drawerShown to true in the beginning shows the overlay
5) having the drawerShown as it currently is doesn't show the overlay at all, even when opened programmatically


Unfortunately I have currently no idea were to go from here, I will try different versions of this lib with different RN versions to come closer to the solution. If anyone has a slightest hint, please let me know!

**Comment by DanielMSchmidt** [comment]
Should be fixed in `1.1.5`, can you verfiy?

**Comment by alxyuu** [comment]
yep, the background works now. that being said, I'm having trouble swiping right to pull out the drawer (it worked maybe 1 out of 10 times). this is with a mouse in the simulator though, as I don't have access to a physical device at the moment.
