### ISSUE TITLE
iOS drawer gesture can be stolen

### ISSUE THREAD

**Issue by ericvicenti** [react-native-community/react-native-drawer-layout#3]
Because the responder is misconfigured, it is possible for multiple gestures to happen at the same time, which results in a bad experience. Halfway through swiping the drawer open, another gesture recognizer could request responder and leave the drawer in a broken state because the current policy is to accept the responder termination request.

So I think the fix is to set the responder termination policy to false:
https://github.com/react-native-community/react-native-drawer-layout/blob/master/src/DrawerLayout.ios.js#L98

This issue is visible on the `react-navigation` examples, which is easy to run with exponent by checking out the repo and then:

```
cd react-navigation/examples/NavigationPlayground/__exponent && xde
```

Tap into the drawer example, start swiping the drawer open, then swipe down and you will see the bug happen as another gesture steals the drawer responder.

**Comment by DanielMSchmidt** [comment]
Hey, thanks for the feedback! I will try your suggested solution today and come up with a PR. Would you mind reviewing it?

**Comment by DanielMSchmidt** [comment]
Hups, closed the wrong issue
