### ISSUE TITLE
Support for both - android and IOs

### ISSUE THREAD

**Issue by codingwithbatista** [react-native-community/react-native-drawer-layout#40]
I have a question:
Has this API  support for both platforms - IOs and Android?

I would like to use this API in my job and i need generate versions of an application to both platforms .

Thanks!

**Comment by DanielMSchmidt** [comment]
Yes, this project supports both. If you want to use the native android code for android, please use [react-native-community/react-native-drawer-layout-polyfill](https://github.com/react-native-community/react-native-drawer-layout-polyfill) instead. Hope this answers your question.

**Comment by codingwithbatista** [comment]
yeah! so, thanks . i'll use it =)
