### ISSUE TITLE
react-native-dismiss-keyboard deprecated

### ISSUE THREAD

**Issue by raynor85** [react-native-community/react-native-drawer-layout#43]
The dependency react-native-dismiss-keyboard is deprecated in favour of the method dismiss() of the Keyboard component which comes within react-native.
https://facebook.github.io/react-native/docs/keyboard.html

**Comment by DanielMSchmidt** [comment]
@raynor85 Thanks for letting me know, it would be great if you could send in a PR for the newer RN versions, I would really appreciate the help 👍

**Comment by raynor85** [comment]
Pull request done. It should also fix CI, since now is broken. #44

**Comment by piranna** [comment]
Any update on this? This is the major problem I'm worried about the [React Native web](https://github.com/react-native-community/react-native-drawer-layout/issues/48) support... :-/

**Comment by DanielMSchmidt** [comment]
Thanks for pinging me, I completely forgot about it in my vacation. Will
release that now

Jesús Leganés-Combarro <notifications@github.com> schrieb am Do., 9. Nov.
2017, 11:44:

**Comment by piranna** [comment]
You are welcome :-)

**Comment by piranna** [comment]
Thanks for merging :-) Any clue when this would be published on npm? :-)

**Comment by DanielMSchmidt** [comment]
Just now as `2.0.0`

**Comment by piranna** [comment]
Thank you so much!!! :-D
