### ISSUE TITLE
it's very slowly 

### ISSUE THREAD

**Issue by cuiken** [react-native-community/react-native-drawer-layout#9]
when i upgrade react-native to 0.42，the drawer response slow in android

**Comment by DanielMSchmidt** [comment]
Which version of react-native-drawer-layout are you using? We changed the implementation from being a polyfill for the native android solution to being a pure JS implementation. (in 1.1.4)) If you switch to [react-native-drawer-layout-polyfill](https://github.com/react-native-community/react-native-drawer-layout-polyfill) instead you will get the native implemenation on Android, which might be faster. Will try to reproduce the problem either way

**Comment by DanielMSchmidt** [comment]
Should be fixed in `1.1.5`, can you verfiy?

**Comment by Ruanyang2015** [comment]
me too,my device is 小米8
